import js from "@eslint/js";
import tseslint from "typescript-eslint";
import prettier from "eslint-config-prettier";

export default tseslint.config(
  {
    ignores: [
      "**/dist/**",
      "**/.next/**",
      "**/node_modules/**",
      "**/coverage/**",
      "**/.pnpm-store/**",
      "**/*.config.js",
      // Generated by Next.js on every build and overwritten if edited.
      "**/next-env.d.ts"
    ]
  },
  js.configs.recommended,
  ...tseslint.configs.strictTypeChecked,
  {
    languageOptions: {
      parserOptions: {
        projectService: true,
        tsconfigRootDir: import.meta.dirname
      }
    },
    rules: {
      "@typescript-eslint/no-floating-promises": "error",
      "@typescript-eslint/no-misused-promises": "error",
      "@typescript-eslint/explicit-function-return-type": ["error", { allowExpressions: true }],
      // Underscore prefix marks a deliberately unused binding. ignoreRestSiblings
      // supports the `const { secret: _omitted, ...rest }` omit idiom.
      "@typescript-eslint/no-unused-vars": [
        "error",
        {
          argsIgnorePattern: "^_",
          varsIgnorePattern: "^_",
          caughtErrorsIgnorePattern: "^_",
          ignoreRestSiblings: true
        }
      ]
    }
  },
  {
    // Migrations are plain JavaScript with JSDoc types (ADR-027) and live outside
    // any TypeScript project, so type-aware rules cannot apply to them. They are
    // still linted for ordinary correctness.
    files: ["packages/database/migrations/**/*.js", "packages/database/seeds/**/*.js"],
    ...tseslint.configs.disableTypeChecked,
    rules: {
      ...tseslint.configs.disableTypeChecked.rules,
      // JSDoc supplies the return types in migrations.
      "@typescript-eslint/explicit-function-return-type": "off"
    }
  },
  {
    // Integration tests deliberately assert against untyped values: raw database
    // rows and parsed HTTP JSON. Casting those to hand-written types would make
    // the test verify our assumptions about a column rather than the column
    // itself, which is the one thing an integration test exists to check.
    files: ["**/*.integration.test.ts"],
    rules: {
      "@typescript-eslint/no-unsafe-member-access": "off",
      "@typescript-eslint/no-unsafe-assignment": "off",
      "@typescript-eslint/no-unsafe-argument": "off",
      "@typescript-eslint/no-unsafe-call": "off",
      "@typescript-eslint/explicit-function-return-type": "off"
    }
  },
  {
    // React components return JSX and the ecosystem conventionally omits the
    // annotation. Requiring it here buys nothing and fights every example a
    // contributor will have seen.
    files: ["**/*.tsx"],
    rules: {
      "@typescript-eslint/explicit-function-return-type": "off"
    }
  },
  prettier
);
