// Generated offline by schema/scripts/generate.mjs; see schema/README.md.
// Copyright 2019-2020 OpenTelemetry Authors; Copyright 2026 Google LLC.
// OTLP and google.rpc sources: Apache-2.0; protobufjs Any descriptor: BSD-3-Clause.
// Source pins: OTLP 790608c4d51e6ffc12210b541e8514cbed9e91a4,
// googleapis ebd1d23ac613b177828dad42ad8dfb13ba498279; protobufjs 7.6.6.
/*
This license applies to all parts of protobuf.js except those files
either explicitly including or referencing a different license or
located in a directory containing a different LICENSE file.

---

Copyright (c) 2016, Daniel Wirtz  All rights reserved.

Redistribution and use in source and binary forms, with or without
modification, are permitted provided that the following conditions are
met:

* Redistributions of source code must retain the above copyright
  notice, this list of conditions and the following disclaimer.
* Redistributions in binary form must reproduce the above copyright
  notice, this list of conditions and the following disclaimer in the
  documentation and/or other materials provided with the distribution.
* Neither the name of its author, nor the names of its contributors
  may be used to endorse or promote products derived from this software
  without specific prior written permission.

THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
"AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR
A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT
OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT
LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
(INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

---

Code generated by the command line utilities is owned by the owner
of the input file used when generating it. This code is not
standalone and requires a support library to be linked with it. This
support library is itself covered by the above license.
*/
import type { INamespace } from "protobufjs";
export const descriptor: INamespace = {
  nested: {
    opentelemetry: {
      nested: {
        proto: {
          nested: {
            collector: {
              nested: {
                logs: {
                  nested: {
                    v1: {
                      nested: {
                        ExportLogsServiceRequest: {
                          fields: {
                            resourceLogs: {
                              rule: "repeated",
                              type: "opentelemetry.proto.logs.v1.ResourceLogs",
                              id: 1
                            }
                          }
                        },
                        ExportLogsServiceResponse: {
                          fields: { partialSuccess: { type: "ExportLogsPartialSuccess", id: 1 } }
                        },
                        ExportLogsPartialSuccess: {
                          fields: {
                            rejectedLogRecords: { type: "int64", id: 1 },
                            errorMessage: { type: "string", id: 2 }
                          }
                        }
                      }
                    }
                  }
                }
              }
            },
            logs: {
              nested: {
                v1: {
                  nested: {
                    ResourceLogs: {
                      fields: {
                        resource: { type: "opentelemetry.proto.resource.v1.Resource", id: 1 },
                        scopeLogs: { rule: "repeated", type: "ScopeLogs", id: 2 },
                        schemaUrl: { type: "string", id: 3 }
                      }
                    },
                    ScopeLogs: {
                      fields: {
                        scope: {
                          type: "opentelemetry.proto.common.v1.InstrumentationScope",
                          id: 1
                        },
                        logRecords: { rule: "repeated", type: "LogRecord", id: 2 },
                        schemaUrl: { type: "string", id: 3 }
                      }
                    },
                    LogRecord: {
                      fields: {
                        timeUnixNano: { type: "fixed64", id: 1 },
                        observedTimeUnixNano: { type: "fixed64", id: 11 },
                        severityNumber: { type: "SeverityNumber", id: 2 },
                        severityText: { type: "string", id: 3 },
                        body: { type: "opentelemetry.proto.common.v1.AnyValue", id: 5 },
                        attributes: {
                          rule: "repeated",
                          type: "opentelemetry.proto.common.v1.KeyValue",
                          id: 6
                        },
                        droppedAttributesCount: { type: "uint32", id: 7 },
                        flags: { type: "fixed32", id: 8 },
                        traceId: { type: "bytes", id: 9 },
                        spanId: { type: "bytes", id: 10 },
                        eventName: { type: "string", id: 12 }
                      }
                    },
                    SeverityNumber: {
                      values: {
                        SEVERITY_NUMBER_UNSPECIFIED: 0,
                        SEVERITY_NUMBER_TRACE: 1,
                        SEVERITY_NUMBER_TRACE2: 2,
                        SEVERITY_NUMBER_TRACE3: 3,
                        SEVERITY_NUMBER_TRACE4: 4,
                        SEVERITY_NUMBER_DEBUG: 5,
                        SEVERITY_NUMBER_DEBUG2: 6,
                        SEVERITY_NUMBER_DEBUG3: 7,
                        SEVERITY_NUMBER_DEBUG4: 8,
                        SEVERITY_NUMBER_INFO: 9,
                        SEVERITY_NUMBER_INFO2: 10,
                        SEVERITY_NUMBER_INFO3: 11,
                        SEVERITY_NUMBER_INFO4: 12,
                        SEVERITY_NUMBER_WARN: 13,
                        SEVERITY_NUMBER_WARN2: 14,
                        SEVERITY_NUMBER_WARN3: 15,
                        SEVERITY_NUMBER_WARN4: 16,
                        SEVERITY_NUMBER_ERROR: 17,
                        SEVERITY_NUMBER_ERROR2: 18,
                        SEVERITY_NUMBER_ERROR3: 19,
                        SEVERITY_NUMBER_ERROR4: 20,
                        SEVERITY_NUMBER_FATAL: 21,
                        SEVERITY_NUMBER_FATAL2: 22,
                        SEVERITY_NUMBER_FATAL3: 23,
                        SEVERITY_NUMBER_FATAL4: 24
                      }
                    }
                  }
                }
              }
            },
            resource: {
              nested: {
                v1: {
                  nested: {
                    Resource: {
                      fields: {
                        attributes: {
                          rule: "repeated",
                          type: "opentelemetry.proto.common.v1.KeyValue",
                          id: 1
                        },
                        droppedAttributesCount: { type: "uint32", id: 2 },
                        entityRefs: {
                          rule: "repeated",
                          type: "opentelemetry.proto.common.v1.EntityRef",
                          id: 3
                        }
                      }
                    }
                  }
                }
              }
            },
            common: {
              nested: {
                v1: {
                  nested: {
                    KeyValue: {
                      fields: {
                        key: { type: "string", id: 1 },
                        value: { type: "AnyValue", id: 2 },
                        keyStrindex: { type: "int32", id: 3 }
                      }
                    },
                    AnyValue: {
                      oneofs: {
                        value: {
                          oneof: [
                            "stringValue",
                            "boolValue",
                            "intValue",
                            "doubleValue",
                            "arrayValue",
                            "kvlistValue",
                            "bytesValue",
                            "stringValueStrindex"
                          ]
                        }
                      },
                      fields: {
                        stringValue: { type: "string", id: 1 },
                        boolValue: { type: "bool", id: 2 },
                        intValue: { type: "int64", id: 3 },
                        doubleValue: { type: "double", id: 4 },
                        arrayValue: { type: "ArrayValue", id: 5 },
                        kvlistValue: { type: "KeyValueList", id: 6 },
                        bytesValue: { type: "bytes", id: 7 },
                        stringValueStrindex: { type: "int32", id: 8 }
                      }
                    },
                    ArrayValue: {
                      fields: { values: { rule: "repeated", type: "AnyValue", id: 1 } }
                    },
                    KeyValueList: {
                      fields: { values: { rule: "repeated", type: "KeyValue", id: 1 } }
                    },
                    EntityRef: {
                      fields: {
                        schemaUrl: { type: "string", id: 1 },
                        type: { type: "string", id: 2 },
                        idKeys: { rule: "repeated", type: "string", id: 3 },
                        descriptionKeys: { rule: "repeated", type: "string", id: 4 }
                      }
                    },
                    InstrumentationScope: {
                      fields: {
                        name: { type: "string", id: 1 },
                        version: { type: "string", id: 2 },
                        attributes: { rule: "repeated", type: "KeyValue", id: 3 },
                        droppedAttributesCount: { type: "uint32", id: 4 }
                      }
                    }
                  }
                }
              }
            }
          }
        }
      }
    },
    google: {
      nested: {
        rpc: {
          nested: {
            Status: {
              fields: {
                code: { type: "int32", id: 1 },
                message: { type: "string", id: 2 },
                details: { rule: "repeated", type: "google.protobuf.Any", id: 3 }
              }
            }
          }
        },
        protobuf: {
          nested: {
            Any: {
              fields: { type_url: { type: "string", id: 1 }, value: { type: "bytes", id: 2 } }
            }
          }
        }
      }
    }
  }
};
