import knex, { type Knex } from "knex";
import { requiredEnv } from "./env.js";
import type { Customer } from "./transform.js";

export function demoDatabase(): Knex {
  return knex({ client: "pg", connection: requiredEnv("DEMO_DATABASE_URL") });
}

/**
 * Create the demo's own customer table.
 *
 * The identity sequence starts at 18492 so the first customer gets the internal
 * ID that `DEMO_SCENARIO.md` section 5 lists as an alias and section 9 requires
 * as a search case. A demo whose identifiers match its own documentation is
 * worth one line of SQL.
 */
export async function ensureCustomerTable(db: Knex): Promise<void> {
  await db.raw(`
    create table if not exists customers (
      id bigint primary key generated by default as identity (start with 18492),
      external_id text not null unique,
      name text not null,
      phone text,
      status text not null,
      created_at timestamptz not null default now()
    )
  `);
}

/** Returns the internal customer ID. Upserts, so re-triggering the demo is safe. */
export async function upsertCustomer(db: Knex, customer: Customer): Promise<number> {
  const rows: unknown = await db("customers")
    .insert({
      external_id: customer.externalId,
      name: customer.name,
      phone: customer.phone,
      status: customer.status
    })
    .onConflict("external_id")
    .merge(["name", "phone", "status"])
    .returning("id");

  if (!Array.isArray(rows) || rows.length === 0) {
    throw new Error("Upserting the customer returned no rows.");
  }

  // pg returns bigint as a string, to avoid losing precision above 2^53.
  const id: unknown = (rows[0] as Record<string, unknown>)["id"];
  return Number(id);
}
